language: python
python:
- '3.2'
- '3.3'
- '3.4'
- '3.5'
- 3.5-dev
- '3.6'
- 3.6-dev
- 3.7-dev
- nightly
sudo: false
before_script:
- chmod +x run
install: pip3 install slackclient
script: ./run --tests && ./run
env:
  global:
    secure: A+c/7RsuSI+EUqBm9uQYy2XWNONJjkphDyDBoZhnCqJ+zbNiQXjEfbPqgEC7Diq9RL/PVCyc13gElpIBTbEMtMIFNes+0VwLEb1etDzn4ahR11/AZE6FD9I2Ni5dK/h1oNPr8GYAY3mbzsgxXrb+ltAqxqJUkCCgAQrhofPhm6OkuHZLsJDDtsD4SLtZw81jXUfDDeRHm9Assf0OE9qvlPv/4U6aUAcKcIEsvUKBcui8FhQdAo7OuFItrmO9HIHZaGls9CxkfUf9LkNcmiZSUV+rAlbnOmHAp/s3CvO4aK7SD2qFMAk/dvIk+dlKujLGugTWYUzt1/WxckyX+7UM3py9xZ1eYJNeG0UOi/d1Za6jjNQCzgFAhh1X+vyQAQREfyTlgRIbLjItkVqhXaE6tJF9+tJEo9Jvn77hLDSLhA8qprl6vb49RwGPOk0i5BiNpe5TdPBtIfqCgMisCqhj3HZnQXp2fBvoqeLYhraNrUyEHVydawkrpK1tMrV2o3tpNKl7ogUl1/2yQBzafIIZCWdlEOO3mKYhL34lF7zyQ1YGzG+8hWrgY8SEDZ/j4ZyQ1h71ZL+6q/v2gBNvJw/rrcxJ2LF/Xb8mhb4M+seloItkvRdpmIbDTm4UrcA6JMhT9D3Dm0cW0s7WUnzMfEtI8/3UZbB6xORjcfcTJljyE9A=
