#!/bin/bash

if command -v python3 &>/dev/null; then
	echo Python 3 is installed, checking for dependencies
	
	VALUES= pip list | grep -F slackclient 
	
	if [ -z '$VALUES' ]; then 
		pip install slackclient -user
	fi	

else 
	echo Please upgrade to Python 3 to run Vulnerbot

fi

